USE [master]
GO

/****** Object:  Database [TASKMANAGER]    Script Date: 4/29/2019 3:36:05 AM ******/
CREATE DATABASE [TASKMANAGER]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskManagerDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TaskManagerDb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TaskManagerDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TaskManagerDb_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TASKMANAGER] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TASKMANAGER].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TASKMANAGER] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TASKMANAGER] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TASKMANAGER] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TASKMANAGER] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TASKMANAGER] SET ARITHABORT OFF 
GO

ALTER DATABASE [TASKMANAGER] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TASKMANAGER] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TASKMANAGER] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TASKMANAGER] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TASKMANAGER] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TASKMANAGER] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TASKMANAGER] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TASKMANAGER] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TASKMANAGER] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TASKMANAGER] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TASKMANAGER] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TASKMANAGER] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TASKMANAGER] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TASKMANAGER] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TASKMANAGER] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TASKMANAGER] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TASKMANAGER] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TASKMANAGER] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TASKMANAGER] SET RECOVERY FULL 
GO

ALTER DATABASE [TASKMANAGER] SET  MULTI_USER 
GO

ALTER DATABASE [TASKMANAGER] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TASKMANAGER] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TASKMANAGER] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TASKMANAGER] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TASKMANAGER] SET  READ_WRITE 
GO


USE [TASKMANAGER]
GO

/****** Object:  Table [dbo].[Task]    Script Date: 4/29/2019 3:36:35 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Task](
	[Task_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Parent_ID] [bigint] NULL,
	[Task_Name] [varchar](50) NULL,
	[Start_Date] [date] NULL,
	[End_Date] [date] NULL,
	[Priority] [int] NULL,
 CONSTRAINT [PK_Task] PRIMARY KEY CLUSTERED 
(
	[Task_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


